### ISSUE TITLE
Resource mapping 

### ISSUE THREAD

**Issue by dovchar** [grsmv/clio#12]
Looks unuseful:
func ControllerRoutes () {
    Get    ("/books",   Books      )
    Get    ("/books/_", Book       )
    Post   ("/books",   BooksCreate)
    Put    ("/books/_", BookUpdate )
    Delete ("/books",   BooksRemove)
    Delete ("/books/*", BookRemove )
}

I think it will be better something like that:

func ControllerRoutes () {
    Resourse ("books",   Books      )
}

**Comment by grsmv** [comment]
Ok, looks good, but I'd like to see it as an additional function of API, neither one and only thing. And we really need to talk about function-calling assumptions using this way to route.

**Comment by grsmv** [comment]
Removed in a name of generators
