### ISSUE TITLE
When I create new app and run it I can see it in browser 

### ISSUE THREAD

**Issue by dovchar** [grsmv/clio#14]
Steps for reproduce:
1. go get github.com/pallada/clio
2. clio create myapp:
error:  open /src/github.com/pallada/clio/templates/config/application.go: no such file or directory
 error:  open /src/github.com/pallada/clio/templates/config/assets.yml: no such file or directory
 error:  open /src/github.com/pallada/clio/templates/config/dependencies: no such file or directory
 error:  open /src/github.com/pallada/clio/templates/config/procfile.yml: no such file or directory
 error:  open /src/github.com/pallada/clio/templates/public/javascripts/vendor/underscore/underscore.js: no such file or directory
 error:  open /src/github.com/pallada/clio/templates/public/javascripts/vendor/backbone/backbone.js: no such file or directory
1. clio run: nothing happen;

What the problem?

**Comment by grsmv** [comment]
Please past here output from your `go env`

**Comment by dovchar** [comment]
GOARCH="386"
GOBIN=""
GOCHAR="8"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dima/Projects/go/clio_test/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_386"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m32 -pthread -fno-common"
CGO_ENABLED="1"

**Comment by dovchar** [comment]
Also when I run app it will be better show status for example:
clio application was running on localhost:4567

**Comment by grsmv** [comment]
Thanks a lots

**Comment by grsmv** [comment]
During creation of app Clio's core assumes that your template files stored in 
`$GOPATH/src/github.com/pallada/clio/templates/` directory. 

Your GOPATH is `/Users/dima/Projects/go/clio_test/` and Clio search for templates in `/`. Please check your Go settings. 

Also, on my computer, message about non existing source in templates looks like:
`error:  open /Users/sergey/go/bin/src/github.com/pallada/clio/templates/public/javascripts/vendor/backbone/backbone.js`
Which shows that Clio searches in GOPATH/*.

P.S. One additional note: if you'll fix your GO settings, don't be bothered by messages about underscore and backbone non existing files - we will move them out of Cio's Core.

**Comment by dovchar** [comment]
yes I fix it. thank you. So now I see application.go file in root when I do 'clio run' everything works like prev. : 
MacBook-Pro-Dmytro:qa dima$ clio run 
 coffee  started
 scss  started

if I do 'go run application.go' I see this:
 MacBook-Pro-Dmytro:qa dima$ go run application.go 
../github.com/pallada/clio/helpers/paths.go:5:5: cannot find package "bitbucket.org/kardianos/osext" in any of:
    /usr/local/go/src/pkg/bitbucket.org/kardianos/osext (from $GOROOT)
    /Users/dima/Projects/go/test/src/bitbucket.org/kardianos/osext (from $GOPATH)

do you know what is it?

**Comment by grsmv** [comment]
Hm, `bitbucket.org/kardianos/osext`  - Package that Clio uses for inner purposes. So we definitely need to do `clio deps` feature.

**Comment by grsmv** [comment]
Dima, all relative issues fixed. Please grab  fresh copy of Clio and test this. After your report I'll close this issue. Thanks

**Comment by dovchar** [comment]
I will do it today. Thank you a lot

**Comment by grsmv** [comment]
Actually, after all that fixes Clio smoothly installs on a fresh server.
