### ISSUE TITLE
Reporting errors to Errbit and Airbrake

### ISSUE THREAD

**Issue by grsmv** [grsmv/clio#54]
Sending error reports to a named serviced. What need to be done:
- Error reporting API
- Plugin for sending reports
- Data for Integration (api key etc) in application's settings.

Requirements:
- Sending error should be non-blocking (sending error reports in a background)

**Comment by grsmv** [comment]
For API calls and "how do the do it" take a look at:
http://robots.thoughtbot.com/writing-a-hoptoad-notifier-contacting-the-toad

**Comment by kelyar** [comment]
Airbnb? :) someone needs a vacation

**Comment by grsmv** [comment]
Haha, definitely :)
